### ISSUE TITLE
Use background modifier Issue

### ISSUE THREAD

**Issue by wwdc14** [lkzhao/UIComponent#15]
If i use background modifier with animator will have problems
This problem occurs in version 0.8.2
![2021-09-14 21 36 40](https://user-images.githubusercontent.com/11381801/133267698-c99f8b50-aefe-4d6b-aae1-565ff2a9b6de.gif)

**Comment by wwdc14** [comment]
The animations of versions before 0.8.1 are normal

**Comment by wwdc14** [comment]
This is test project
[TestUIComponent.zip](https://github.com/lkzhao/UIComponent/files/7189907/TestUIComponent.zip)

**Comment by lkzhao** [comment]
Thanks for the test project. Fixed in https://github.com/lkzhao/UIComponent/releases/tag/0.9.0
