### ISSUE TITLE
Podspec missing Dependency `BaseToolbox`

### ISSUE THREAD

**Issue by wwdc14** [lkzhao/UIComponent#16]

**Comment by lkzhao** [comment]
Would you be able to use SPM? I'm thinking about deprecating Podspec.

**Comment by lkzhao** [comment]
Otherwise, I would appreciate a PR since I don't use CocoaPods anymore myself.

**Comment by wwdc14** [comment]
Okay, give me some time, I will try to transfer to SPM, if it fails, I will PR Podspec 😄
