### ISSUE TITLE
HStack has bug

### ISSUE THREAD

**Issue by wwdc14** [lkzhao/UIComponent#5]
Hi,

I use HStack Layout Component has a long string, I hope it will wrap, but it goes beyond the screen.

Is it possible to add `CSS Flex Wrap` properties to the Stack component?

e.g
```
HStack(wrap: .wrap || .noWrap) {
    ......
}
```

this my codes

**HStack code**
```swift
HStack {
    Text("long long long long long long long long long long long long long long long long long long long long long long long long long long long long text")
}.size(width: .percentage(1)).inset(h: 10, v: 10)
```

**VStack code**
```swift
VStack {
    Text("long long long long long long long long long long long long long long long long long long long long long long long long long long long long text")
}.size(width: .percentage(1)).inset(h: 10, v: 10)
```

**Also exceed the screen boundary**
```swift
VStack {
    HStack {
        VStack {
            Text("long long long long long long long long long long long long long long long long long long long long long long long long long long long long text")
        }
    }
}.size(width: .percentage(1)).inset(h: 10, v: 10)
```

HStack unusual
<img width="442" alt="iShot2021-07-16 23 33 49" src="https://user-images.githubusercontent.com/11381801/125973200-eacc5588-9b2f-47cb-af1b-6fbf3d471581.png">

VStack normal
<img width="442" alt="iShot2021-07-16 23 33 49" src="https://user-images.githubusercontent.com/11381801/125972671-5930015a-a27a-4232-9b93-245a9e362429.png">

**Comment by lkzhao** [comment]
Talked offline and on #6. Not going to update `HStack` to fix this issue, but you could use the new `FlexRow` or `Flow` to create a wrapping `HStack`.
